### ISSUE TITLE
errors testing with pruned_0.35 model

### ISSUE THREAD

**Issue by CornerSluggish** [xingyul/Sparse-Winograd-CNN#1]
1. I tried to test one image which is from ILSVRC2012 with the provided pre-trained pruned model (Density 0.35), but somehow the 'ReLU' function seemed undefined.

Traceback (most recent call last):
  File "./imagenet-resnet-transWino-prune.py", line 407, in <module>
    SyncMultiGPUTrainerParameterServer(config).train()
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/train/base.py", line 335, in __new__
    return old_trainer(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/trainv1/multigpu.py", line 66, in __init__
    super(SyncMultiGPUTrainerParameterServer, self).__init__(config)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/trainv1/base.py", line 73, in __init__
    self._setup()   # subclass will setup the graph and InputSource
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/trainv1/multigpu.py", line 75, in _setup
    self.model.get_optimizer)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/graph_builder/training.py", line 149, in build
    grad_list = DataParallelBuilder.build_on_towers(self.towers, get_grad_fn, devices)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/graph_builder/training.py", line 106, in build_on_towers
    ret.append(func())
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/trainv1/multigpu.py", line 74, in <lambda>
    *self._input_source.get_input_tensors()),
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/graph_builder/model_desc.py", line 180, in _build_graph_get_grads
    cost = self._build_graph_get_cost(*inputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/graph_builder/model_desc.py", line 168, in _build_graph_get_cost
    self.build_graph(*inputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/graph_builder/model_desc.py", line 116, in build_graph
    self._build_graph(inputs)
File "./imagenet-resnet-transWino-prune.py", line 140, in _build_graph
    l =ReLU(l, 'res2b_1_relu')
NameError: name 'ReLU' is not defined

2. After replacing 'ReLU' with 'tf.nn.relu', it looked like the 1st problem is fixed, and _build_graph worked successfully. However, another 'DataLossError' error occurred. Did the replacement of ReLU function cause this problem or the pre-trained model has broken or maybe there are some other implicit problems?

Traceback (most recent call last):
  File "./imagenet-resnet-transWino-prune.py", line 407, in <module>
    SyncMultiGPUTrainerParameterServer(config).train()
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/trainv1/base.py", line 109, in train
    self.setup()
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/trainv1/base.py", line 144, in setup
    self._config.session_init._setup_graph()
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/tfutils/sessinit.py", line 113, in _setup_graph
    dic = self._get_restore_dict()
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/tfutils/sessinit.py", line 162, in _get_restore_dict
    self._match_vars(f)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/tfutils/sessinit.py", line 129, in _match_vars
    reader, chkpt_vars = SaverRestore._read_checkpoint_vars(self.path)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/tfutils/sessinit.py", line 123, in _read_checkpoint_vars
    reader = tf.train.NewCheckpointReader(model_path)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 223, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.DataLossError: not an sstable (bad magic number)
PrefetchDataZMQ successfully cleaned-up.

By the way, I did NOT add a new OP in TensorFlow, I just added some flags like '-ltensorflow_framework', ' -D_GLIBCXX_USE_CXX11_ABI=0' and etc. in .../winograd2x2_cublas/winograd2x2_conv/Makefile to avoid 'undefined symbol: _ZTIN10tensorflow8OpKernelE' problem. If this may cause other problems, would you please release TensorFlow C++ OP code?

Thank you

**Comment by xingyul** [comment]
For 1., I replaced ReLU() with tf.nn.reluI(). Thanks for catching this!
For 2., what tensorflow version are you using?
I have released the TF C++ Op code in winograd2x2_cublas/ directory.

**Comment by CornerSluggish** [comment]
Thank you so much for your reply!
I'll check the winograd2x2_cublas/ directory and try again!

BTW, I use Tensorflow 1.5.
And I think I already did 'the adding an OP' part but I just didn't know it.
So, it might be the Tensorflow version that cause this problem or I try to test one image but I alter the code in a wrong way.
Thanks again!
