### ISSUE TITLE
CUDA_ERROR_ILLEGAL_ADDRESS and CUDNN_STATUS_EXECUTION_FAILED in batchnorm when training

### ISSUE THREAD

**Issue by huangdi95** [xingyul/Sparse-Winograd-CNN#4]
Hi, @xingyul .

Thanks for your sharing!

When training ResNet-18 from scratch, I encountered the following problem:

```
2018-07-17 19:36:41.416346: E tensorflow/stream_executor/cuda/cuda_driver.cc:802] failed to enqueue async memset operation: CUDA_ERROR_ILLEGAL_ADDRESS
2018-07-17 19:36:41.416404: I tensorflow/stream_executor/stream.cc:4339] stream 0x7d9b570 did not memzero GPU location; source: 0x7f8864f07ab0
2018-07-17 19:36:41.416454: E tensorflow/stream_executor/cuda/cuda_dnn.cc:2229] failed to enqueue forward batch normalization on stream: CUDNN_STATUS_EXECUTION_FAILED
```

But I can train ResNet-18 in Tensorpack successfully.

In fact, using pre-trained model has the same problem.

I have tried some methods found online but on one works, and I have no idea now.

Is it something wrong with BatchNorm()?

Or something wrong with GPU?

Could you help me plz...

ubuntu: 16.04
gcc: 4.8.5
cuda: 8.0
cudnn: 6.0
Tensorflow: 1.3.0 (installed by pip)
Tensorpack: 0.8.0 commit [0086e156c](https://github.com/tensorpack/tensorpack/commit/0086e156c7a8c769fffea2214242c1b5767359d7)

The full message:

```
[0717 20:15:12 @base.py:191] Start Epoch 1 ...
  0%|                                                                                                                                                                |0/128000[00:00<?,?it/s]
2018-07-17 20:15:13.426854: E tensorflow/stream_executor/cuda/cuda_driver.cc:802] failed to enqueue async memset operation: CUDA_ERROR_ILLEGAL_ADDRESS
2018-07-17 20:15:13.426928: I tensorflow/stream_executor/stream.cc:4339] stream 0x8168d80 did not memzero GPU location; source: 0x7f35174ffab0
2018-07-17 20:15:13.426986: E tensorflow/stream_executor/cuda/cuda_dnn.cc:2229] failed to enqueue forward batch normalization on stream: CUDNN_STATUS_EXECUTION_FAILED

2018-07-17 20:15:13.444887: W tensorflow/core/kernels/queue_base.cc:295] _0_QueueInput/input_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "./imagenet-resnet-transWino-prune.py", line 391, in <module>
[0717 20:15:13 @input_source.py:148] EnqueueThread QueueInput/input_queue Exited.
    SyncMultiGPUTrainerParameterServer(config).train()
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.0-py2.7.egg/tensorpack/trainv1/base.py", line 110, in train
    self.main_loop()
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.0-py2.7.egg/tensorpack/trainv1/base.py", line 197, in main_loop
    self.run_step()  # implemented by subclass
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.0-py2.7.egg/tensorpack/trainv1/base.py", line 124, in run_step
    self.hooked_sess.run(self.train_op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 518, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 862, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 818, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 972, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 818, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: cuDNN launch failure : input shape ([2,56,56,64])
         [[Node: tower0/res2a_bn2b/FusedBatchNorm = FusedBatchNorm[T=DT_FLOAT, data_format="NHWC", epsilon=1.0000001e-05, is_training=true, _device="/job:localhost/replica:0/task:0/gpu:0"](tower0/Winograd_W2a_2a/Winograd2x2Conv, res2a_bn2b/gamma/read, res2a_bn2b/beta/read, tower0/res2a_bn2b/Const, tower0/res2a_bn2b/Const_1)]]
         [[Node: tower0/linear/output/_967 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_929_tower0/linear/output", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'tower0/res2a_bn2b/FusedBatchNorm', defined at:
  File "./imagenet-resnet-transWino-prune.py", line 391, in <module>
    SyncMultiGPUTrainerParameterServer(config).train()
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.0-py2.7.egg/tensorpack/train/base.py", line 327, in __new__
    return old_trainer(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.0-py2.7.egg/tensorpack/trainv1/multigpu.py", line 66, in __init__
    super(SyncMultiGPUTrainerParameterServer, self).__init__(config)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.0-py2.7.egg/tensorpack/trainv1/base.py", line 73, in __init__
    self._setup()   # subclass will setup the graph and InputSource
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.0-py2.7.egg/tensorpack/trainv1/multigpu.py", line 75, in _setup
    self.model.get_optimizer)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.0-py2.7.egg/tensorpack/graph_builder/training.py", line 153, in build
    grad_list = DataParallelBuilder.build_on_towers(self.towers, get_grad_fn, devices)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.0-py2.7.egg/tensorpack/graph_builder/training.py", line 113, in build_on_towers
    ret.append(func())
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.0-py2.7.egg/tensorpack/trainv1/multigpu.py", line 74, in <lambda>
    *self._input_source.get_input_tensors()),
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.0-py2.7.egg/tensorpack/graph_builder/model_desc.py", line 180, in _build_graph_get_grads
    cost = self._build_graph_get_cost(*inputs)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.0-py2.7.egg/tensorpack/graph_builder/model_desc.py", line 168, in _build_graph_get_cost
    self.build_graph(*inputs)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.0-py2.7.egg/tensorpack/graph_builder/model_desc.py", line 116, in build_graph
    self._build_graph(inputs)
  File "./imagenet-resnet-transWino-prune.py", line 120, in _build_graph
    l_bra = BatchNorm('res2a_bn2b', l_bra)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.0-py2.7.egg/tensorpack/models/registry.py", line 125, in wrapped_func
    outputs = func(*args, **actual_args)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.0-py2.7.egg/tensorpack/models/batch_norm.py", line 136, in BatchNorm
    is_training=True, data_format=data_format)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_impl.py", line 821, in fused_batch_norm
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 1280, in _fused_batch_norm
    is_training=is_training, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): cuDNN launch failure : input shape ([2,56,56,64])
         [[Node: tower0/res2a_bn2b/FusedBatchNorm = FusedBatchNorm[T=DT_FLOAT, data_format="NHWC", epsilon=1.0000001e-05, is_training=true, _device="/job:localhost/replica:0/task:0/gpu:0"](tower0/Winograd_W2a_2a/Winograd2x2Conv, res2a_bn2b/gamma/read, res2a_bn2b/beta/read, tower0/res2a_bn2b/Const, tower0/res2a_bn2b/Const_1)]]
         [[Node: tower0/linear/output/_967 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_929_tower0/linear/output", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

PrefetchDataZMQ successfully cleaned-up.
```

**Comment by huangdi95** [comment]
Sorry, it is a problem caused by a brokendown server. I have solved it by changing to another server.
